# Assign Parameters
param (
    [string]$site =""
)

# Call to get HTML Data
./getHTML.ps1 -site $site

# Run the Node App
if ($site -ne ""){              # Make sure site is found
    npm start                   # Call the Start Script for NPM
}




# SIG # Begin signature block
# MIIFuQYJKoZIhvcNAQcCoIIFqjCCBaYCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUwrVWZp6kBDHHu95gEvpau9wT
# 6M+gggNCMIIDPjCCAiqgAwIBAgIQeI4UjHW/goBJUu2bLdM8dDAJBgUrDgMCHQUA
# MCwxKjAoBgNVBAMTIVBvd2VyU2hlbGwgTG9jYWwgQ2VydGlmaWNhdGUgUm9vdDAe
# Fw0xODAxMjMxNjU5MjlaFw0zOTEyMzEyMzU5NTlaMBoxGDAWBgNVBAMTD1Bvd2Vy
# U2hlbGwgVXNlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANBg9qmI
# Td1AC69KsNvfMVCO/gNIwsqHHG8feTALR5N03/xmK+4n12LipSJYvdrQN8PGtBE7
# nq/IL/qEYbP0Tljis0+JBr4hmjqeR6lWrMf6QKNgwvPONRIa3SzSIz6DnhV4xJI+
# DSMvHSEgc8yjfm8VCH/6qXWt8euW0ArdxH/5v33QGD9uRDWdui7jyhUmwkCthwO8
# uI2AdSZm4Wc2DIs4QPKMTSFlPhQHmk3EdAxdtg9vawTeak62IJA7Mp0LKFmgy865
# j/HeBbImYiUlCdRCzkd35BkWwsO1YRyzGzGE54yuq+icz6Sl7GFC/MnIPt4y2Zxf
# 9ceUwUu/KjJ837UCAwEAAaN2MHQwEwYDVR0lBAwwCgYIKwYBBQUHAwMwXQYDVR0B
# BFYwVIAQ/EqVYwoms6P1Z8QegbdQzqEuMCwxKjAoBgNVBAMTIVBvd2VyU2hlbGwg
# TG9jYWwgQ2VydGlmaWNhdGUgUm9vdIIQaT3EtOSEdYxMx5lkR6laKTAJBgUrDgMC
# HQUAA4IBAQCNv/hKENGf5QKt50vhjjrMOfzDlwPh3e6syJWKxQcoFUfW1I1HSmk2
# SxZS9M6gQ0jpK0ecwKMTv2poTfPlDtG5XKGj4xA/bRX0+AexsekzYTCx5uvbRgM5
# TYvAmHyyy8buF9ufAawGFQYGY9X1DrRtRi24kjLaw/LCrmX9ASzzhP68fRswY9JG
# o1nUZoRcX7Py7ELFTdT3aaHtY2G8ozY+feDrUU0k9946gG7vpa71t2tOGl1lTXNP
# JQXBXCIS4ipEmNAVgIXY6VohbB5nHu++mw8sJGCU2CLtkMWpgdgok9yclgqjs04t
# l6WNhkqVXsJk20/gEcgCp9qdb8R7CMVKMYIB4TCCAd0CAQEwQDAsMSowKAYDVQQD
# EyFQb3dlclNoZWxsIExvY2FsIENlcnRpZmljYXRlIFJvb3QCEHiOFIx1v4KASVLt
# my3TPHQwCQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJ
# KoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQB
# gjcCARUwIwYJKoZIhvcNAQkEMRYEFOR4dS+pdE3WuSFRzC2JCL2z7O+8MA0GCSqG
# SIb3DQEBAQUABIIBAD5Re41OEzAlYTLPRlJgP6XP6z+7zqRqwaX/V45jTE3Ts7Js
# C8s5CEHpOe6RHZtM4SZrYoAys9ubec8r79V6Df4tZ9CgrbNLqwZfkek6q9N8Jrto
# cPOhy8oeF5KifGL75XQy5umAL4/TyiojUA6y986vxWbBvDxp6ZOBr5nY34RKtbL+
# ySBuBgH411wZXZMcmGuJLh3WfhOBS2fLkhE2jJepjCrsvZE6ihgeC6KgsQfR7pqb
# crTflZQ6tCvjPQJuPzo0GLzGdtvYJLdWZSlSmRHZfRiZeSff0/6eFcl3tuq/6XQk
# 5NfW/LoiTi6eCh81HP2WuMCFljBJhbS8Q3h/Epw=
# SIG # End signature block
